#!/usr/bin/env bash


set -o errexit
set -o nounset
set -o pipefail


working_dir = "$($dirname ${0})"


source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

if[[ -z ${1+x}]]
then
    message_error "Please Provide filename; Filename can not be empty."
    exit 1
fi


backup_filename= "${BACKUP_FILE_PREFIX}/${1}"

if[[ ! -f ${backup_filename}]]; then
    message_error "No backup file found!"
    exit 1
fi

message_welcome " Resatoring from '${POSTGRES_DB}' to file: '${backup_filename}' "

if[[ "${POSTGRES_USER}"== "postgres"]]; then
    
    message_error " You cant bakup in same user : '${POSGRS_USER}'"
    
fi

export PG_HOST =       ${POSTGRES_HOST}
export PGPORT =        ${POSTGRES_PORT}
export PGUSER =        ${POSTGRES_USER}
export PGPASSWORD =    ${POSTGRES_PASSWORD}
export PGDATABASE =    ${POSTGRES_DB}
