#!/bin/bash

set -o errexit
set -o nounset

exec watchfiles celery.__main__.main --args '--app authors_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\"'

echo "FLOWER executed"



# exec watchfiles celery.__main__.main --args '--app authors_api.celery worker -l INFO'